<a href="https://colab.research.google.com/github/Architag1503/Colab/blob/main/SequentialModel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Setup and Data Loading
This section handles the initial setup, including importing necessary libraries and loading the dataset.

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

### Import Libraries
This cell imports all the required libraries for data manipulation (pandas, numpy), visualization (seaborn, matplotlib), and deep learning (tensorflow, keras).

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/dataset/Quote_Dataset/quotes_dataset.csv")

### Load Dataset
Loads the quotes dataset from a CSV file into a pandas DataFrame. This dataset will be used for training the language model.

In [ ]:
df.head()

,Qoute,Author,Tag
0,“The world as we have created it is a process ...,Albert Einstein,"['change', 'deep-thoughts', 'thinking', 'world']"
1,"“It is our choices, Harry, that show what we t...",J.K. Rowling,"['abilities', 'choices']"
2,“There are only two ways to live your life. On...,Albert Einstein,"['inspirational', 'life', 'live', 'miracle', '..."
3,"“The person, be it gentleman or lady, who has ...",Jane Austen,"['aliteracy', 'books', 'classic', 'humor']"
4,"“Imperfection is beauty, madness is genius and...",Marilyn Monroe,"['be-yourself', 'inspirational']"

### Display DataFrame Head
Shows the first few rows of the DataFrame to give an initial look at the data structure and content.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Qoute   100 non-null    object
 1   Author  100 non-null    object
 2   Tag     100 non-null    object
dtypes: object(3)
memory usage: 2.5+ KB

### Display DataFrame Information
Provides a concise summary of the DataFrame, including the number of non-null entries, data types, and memory usage. This helps in understanding data completeness and types.

In [ ]:
df.describe()

,Qoute,Author,Tag
count,100,100,100
unique,100,50,84
top,“The world as we have created it is a process ...,Albert Einstein,['love']
freq,1,10,4

### Display DataFrame Description
Generates descriptive statistics of the DataFrame, summarizing the central tendency, dispersion, and shape of the dataset's distribution. Useful for numerical columns, but here it provides insights into unique values for object types.

In [ ]:
df['Qoute'][0]

'“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”'

### Access a Single Quote
Demonstrates how to access a specific quote from the 'Qoute' column by its index.

In [ ]:
df.shape

(100, 3)

### Display DataFrame Shape
Outputs the dimensions of the DataFrame (number of rows, number of columns).

In [ ]:
quotes = df['Qoute']
quotes.head()

0    “The world as we have created it is a process ...
1    “It is our choices, Harry, that show what we t...
2    “There are only two ways to live your life. On...
3    “The person, be it gentleman or lady, who has ...
4    “Imperfection is beauty, madness is genius and...
Name: Qoute, dtype: object

In [ ]:
# Extract the 'Qoute' column, which contains the text data we want to process.
quotes = df['Qoute']
# Display the first few quotes to verify the extraction.
quotes.head()

0    “The world as we have created it is a process ...
1    “It is our choices, Harry, that show what we t...
2    “There are only two ways to live your life. On...
3    “The person, be it gentleman or lady, who has ...
4    “Imperfection is beauty, madness is genius and...
Name: Qoute, dtype: object

## Data Preprocessing
This section focuses on cleaning and preparing the text data for training the neural network.

In [ ]:
quotes = quotes.str.lower()

### Convert Text to Lowercase
Converts all characters in the quotes to lowercase. This helps in reducing the vocabulary size by treating words like 'The' and 'the' as the same.

In [ ]:
import string
translator = str.maketrans('' , '' , string.punctuation)
quotes = quotes.apply(lambda x : x.translate(translator))

### Remove Punctuation
Removes all punctuation from the quotes. Punctuation marks are typically not relevant for word prediction in this context and can be removed to simplify the text.

In [ ]:
quotes.head()

0    “the world as we have created it is a process ...
1    “it is our choices harry that show what we tru...
2    “there are only two ways to live your life one...
3    “the person be it gentleman or lady who has no...
4    “imperfection is beauty madness is genius and ...
Name: Qoute, dtype: object

### Display Cleaned Quotes Head
Shows the first few quotes again after they have been converted to lowercase and had punctuation removed, verifying the preprocessing steps.

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

### Import Tokenizer
Imports the `Tokenizer` class from `tensorflow.keras.preprocessing.text`, which is essential for converting text into numerical sequences suitable for neural networks.

In [ ]:
vocab_size = 763

tokenizer = Tokenizer(num_words=vocab_size)
tokenizer.fit_on_texts(quotes)

### Initialize and Fit Tokenizer
Initializes the `Tokenizer` to process the text. `num_words` is set to the determined `vocab_size` to limit the vocabulary. The tokenizer is then fitted on the `quotes` data to build its vocabulary.

In [ ]:
word_index = tokenizer.word_index
# Update vocab_size to reflect the actual number of unique words + 1
# +1 is for the out-of-vocabulary token or 0-indexed padding.
vocab_size = len(word_index) + 1
print(f"Updated vocabulary size: {vocab_size}")
list(word_index.items())[:10]

Updated vocabulary size: 763

[('you', 1),
 ('to', 2),
 ('is', 3),
 ('the', 4),
 ('a', 5),
 ('of', 6),
 ('and', 7),
 ('i', 8),
 ('it', 9),
 ('not', 10)]

### Determine and Update Vocabulary Size
Extracts the word-to-index mapping from the tokenizer. The `vocab_size` is then dynamically updated to the actual number of unique words found in the dataset plus one (for potential padding or out-of-vocabulary tokens). This ensures the model's embedding layer and output layer dimensions match the true vocabulary size.

In [ ]:
sequence = tokenizer.texts_to_sequences(quotes)

### Convert Text to Sequences
Converts each cleaned quote into a sequence of integers, where each integer represents a word in the tokenizer's vocabulary.

In [ ]:
quotes[0]

'“the world as we have created it is a process of our thinking it cannot be changed without changing our thinking”'

### Display a Cleaned Quote
Displays the first cleaned quote (text format) to compare with its numerical sequence.

In [ ]:
print(sequence[0])

[30, 70, 23, 50, 20, 276, 9, 3, 5, 277, 6, 71, 175, 9, 278, 11, 279, 72, 280, 71, 176]

### Display a Numerical Sequence
Displays the numerical sequence corresponding to the first quote. This shows how words are mapped to integers.

In [ ]:
for i in range(3):
  print(quotes[i])

“the world as we have created it is a process of our thinking it cannot be changed without changing our thinking”
“it is our choices harry that show what we truly are far more than our abilities”
“there are only two ways to live your life one is as though nothing is a miracle the other is as though everything is a miracle”

### Loop and Print First Three Cleaned Quotes
Iterates and prints the first three cleaned quotes in their text format.

In [ ]:
for i in range(3):
  print(sequence[i])

[30, 70, 23, 50, 20, 276, 9, 3, 5, 277, 6, 71, 175, 9, 278, 11, 279, 72, 280, 71, 176]
[51, 3, 71, 281, 128, 12, 282, 21, 50, 177, 22, 283, 36, 44, 71, 284]
[80, 22, 45, 178, 179, 2, 53, 17, 54, 31, 3, 23, 180, 104, 3, 5, 285, 4, 129, 3, 23, 180, 81, 3, 5, 286]

### Loop and Print First Three Numerical Sequences
Iterates and prints the numerical sequences for the first three quotes.

In [ ]:
X = []
y = []

for seq in sequence:
  for i in range(1 , len(seq)):
    input_seq = seq[:i]
    output_seq = seq[i]
    X.append(input_seq)
    y.append(output_seq)

### Prepare Input (X) and Output (y) Sequences
This loop creates the training pairs (input sequence `X` and target word `y`) for the language model. For each sentence, it generates multiple input-output pairs by taking progressively longer prefixes of the sentence as input and the next word as the target.

In [ ]:
X

[[30],
 [30, 70],
 [30, 70, 23],
 [30, 70, 23, 50],
 [30, 70, 23, 50, 20],
 [30, 70, 23, 50, 20, 276],
 [30, 70, 23, 50, 20, 276, 9],
 [30, 70, 23, 50, 20, 276, 9, 3],
 [30, 70, 23, 50, 20, 276, 9, 3, 5],
 [30, 70, 23, 50, 20, 276, 9, 3, 5, 277],
 [30, 70, 23, 50, 20, 276, 9, 3, 5, 277, 6],
 [30, 70, 23, 50, 20, 276, 9, 3, 5, 277, 6, 71],
 [30, 70, 23, 50, 20, 276, 9, 3, 5, 277, 6, 71, 175],
 [30, 70, 23, 50, 20, 276, 9, 3, 5, 277, 6, 71, 175, 9],
 [30, 70, 23, 50, 20, 276, 9, 3, 5, 277, 6, 71, 175, 9, 278],
 [30, 70, 23, 50, 20, 276, 9, 3, 5, 277, 6, 71, 175, 9, 278, 11],
 [30, 70, 23, 50, 20, 276, 9, 3, 5, 277, 6, 71, 175, 9, 278, 11, 279],
 [30, 70, 23, 50, 20, 276, 9, 3, 5, 277, 6, 71, 175, 9, 278, 11, 279, 72],
 [30, 70, 23, 50, 20, 276, 9, 3, 5, 277, 6, 71, 175, 9, 278, 11, 279, 72, 280],
 [30,
  70,
  23,
  50,
  20,
  276,
  9,
  3,
  5,
  277,
  6,
  71,
  175,
  9,
  278,
  11,
  279,
  72,
  280,
  71],
 [51],
 [51, 3],
 [51, 3, 71],
 [51, 3, 71, 281],
 [51, 3, 71, 281, 128],
 [51, 3, 71, 281, 128, 12],
 [51, 3, 71, 281, 128, 12, 282],
 [51, 3, 71, 281, 128, 12, 282, 21],
 [51, 3, 71, 281, 128, 12, 282, 21, 50],
 [51, 3, 71, 281, 128, 12, 282, 21, 50, 177],
 [51, 3, 71, 281, 128, 12, 282, 21, 50, 177, 22],
 [51, 3, 71, 281, 128, 12, 282, 21, 50, 177, 22, 283],
 [51, 3, 71, 281, 128, 12, 282, 21, 50, 177, 22, 283, 36],
 [51, 3, 71, 281, 128, 12, 282, 21, 50, 177, 22, 283, 36, 44],
 [51, 3, 71, 281, 128, 12, 282, 21, 50, 177, 22, 283, 36, 44, 71],
 [80],
 [80, 22],
 [80, 22, 45],
 [80, 22, 45, 178],
 [80, 22, 45, 178, 179],
 [80, 22, 45, 178, 179, 2],
 [80, 22, 45, 178, 179, 2, 53],
 [80, 22, 45, 178, 179, 2, 53, 17],
 [80, 22, 45, 178, 179, 2, 53, 17, 54],
 [80, 22, 45, 178, 179, 2, 53, 17, 54, 31],
 [80, 22, 45, 178, 179, 2, 53, 17, 54, 31, 3],
 [80, 22, 45, 178, 179, 2, 53, 17, 54, 31, 3, 23],
 [80, 22, 45, 178, 179, 2, 53, 17, 54, 31, 3, 23, 180],
 [80, 22, 45, 178, 179, 2, 53, 17, 54, 31, 3, 23, 180, 104],
 [80, 22, 45, 178, 179, 2, 53, 17, 54, 31, 3, 23, 180, 104, 3],
 [80, 22, 45, 178, 179, 2, 53, 17, 54, 31, 3, 23, 180, 104, 3, 5],
 [80, 22, 45, 178, 179, 2, 53, 17, 54, 31, 3, 23, 180, 104, 3, 5, 285],
 [80, 22, 45, 178, 179, 2, 53, 17, 54, 31, 3, 23, 180, 104, 3, 5, 285, 4],
 [80, 22, 45, 178, 179, 2, 53, 17, 54, 31, 3, 23, 180, 104, 3, 5, 285, 4, 129],
 [80,
  22,
  45,
  178,
  179,
  2,
  53,
  17,
  54,
  31,
  3,
  23,
  180,
  104,
  3,
  5,
  285,
  4,
  129,
  3],
 [80,
  22,
  45,
  178,
  179,
  2,
  53,
  17,
  54,
  31,
  3,
  23,
  180,
  104,
  3,
  5,
  285,
  4,
  129,
  3,
  23],
 [80,
  22,
  45,
  178,
  179,
  2,
  53,
  17,
  54,
  31,
  3,
  23,
  180,
  104,
  3,
  5,
  285,
  4,
  129,
  3,
  23,
  180],
 [80,
  22,
  45,
  178,
  179,
  2,
  53,
  17,
  54,
  31,
  3,
  23,
  180,
  104,
  3,
  5,
  285,
  4,
  129,
  3,
  23,
  180,
  81],
 [80,
  22,
  45,
  178,
  179,
  2,
  53,
  17,
  54,
  31,
  3,
  23,
  180,
  104,
  3,
  5,
  285,
  4,
  129,
  3,
  23,
  180,
  81,
  3],
 [80,
  22,
  45,
  178,
  179,
  2,
  53,
  17,
  54,
  31,
  3,
  23,
  180,
  104,
  3,
  5,
  285,
  4,
  129,
  3,
  23,
  180,
  81,
  3,
  5],
 [30],
 [30, 105],
 [30, 105, 11],
 [30, 105, 11, 9],
 [30, 105, 11, 9, 287],
 [30, 105, 11, 9, 287, 32],
 [30, 105, 11, 9, 287, 32, 288],
 [30, 105, 11, 9, 287, 32, 288, 18],
 [30, 105, 11, 9, 287, 32, 288, 18, 73],
 [30, 105, 11, 9, 287, 32, 288, 18, 73, 10],
 [30, 105, 11, 9, 287, 32, 288, 18, 73, 10, 289],
 [30, 105, 11, 9, 287, 32, 288, 18, 73, 10, 289, 13],
 [30, 105, 11, 9, 287, 32, 288, 18, 73, 10, 289, 13, 5],
 [30, 105, 11, 9, 287, 32, 288, 18, 73, 10, 289, 13, 5, 55],
 [30, 105, 11, 9, 287, 32, 288, 18, 73, 10, 289, 13, 5, 55, 290],
 [30, 105, 11, 9, 287, 32, 288, 18, 73, 10, 289, 13, 5, 55, 290, 82],
 [30, 105, 11, 9, 287, 32, 288, 18, 73, 10, 289, 13, 5, 55, 290, 82, 11],
 [30, 105, 11, 9, 287, 32, 288, 18, 73, 10, 289, 13, 5, 55, 290, 82, 11, 291],
 [293],
 [293, 3],
 [293, 3, 294],
 [293, 3, 294, 295],
 [293, 3, 294, 295, 3],
 [293, 3, 294, 295, 3, 130],
 [293, 3, 294, 295, 3, 130, 7],
 [293, 3, 294, 295, 3, 130, 7, 26],
 [293, 3, 294, 295, 3, 130, 7, 26, 131],
 [293, 3, 294, 295, 3, 130, 7, 26, 131, 2],
 [293, 3, 294, 295, 3, 130, 7, 26, 131, 2, 11],
 [293, 3, 294, 295, 3, 130, 7, 26, 131, 2, 11, 181],
 [293, 3, 294, 295, 3, 130, 7, 26, 131, 2, 11, 181, 296],
 [293, 3, 294, 295, 3, 130, 7, 26, 131, 2, 11, 181, 296, 44],
 [293, 3, 294, 295, 3, 130, 7, 26, 131, 2, 11, 181, 296, 44, 181],
 [298],
 [298, 10],
 [298, 10, 2],
 [298, 10, 2, 106],
 [298, 10, 2, 106, 5],
 [298, 10, 2, 106, 5, 83],
 [298, 10, 2, 106, 5, 83, 6],
 [298, 10, 2, 106, 5, 83, 6, 299],
 [298, 10, 2, 106, 5, 83, 6, 299, 300],
 [298, 10, 2, 106, 5, 83, 6, 299, 300, 106],
 [298, 10, 2, 106, 5, 83, 6, 299, 300, 106, 5],
 [298, 10, 2, 106, 5, 83, 6, 299, 300, 106, 5, 83],
 [298, 10, 2, 106, 5, 83, 6, 299, 300, 106, 5, 83, 6],
 [51],
 [51, 3],
 [51, 3, 131],
 [51, 3, 131, 2],
 [51, 3, 131, 2, 11],
 [51, 3, 131, 2, 11, 302],
 [51, 3, 131, 2, 11, 302, 33],
 [51, 3, 131, 2, 11, 302, 33, 21],
 [51, 3, 131, 2, 11, 302, 33, 21, 1],
 [51, 3, 131, 2, 11, 302, 33, 21, 1, 22],
 [51, 3, 131, 2, 11, 302, 33, 21, 1, 22, 44],
 [51, 3, 131, 2, 11, 302, 33, 21, 1, 22, 44, 2],
 [51, 3, 131, 2, 11, 302, 33, 21, 1, 22, 44, 2, 11],
 [51, 3, 131, 2, 11, 302, 33, 21, 1, 22, 44, 2, 11, 182],
 [51, 3, 131, 2, 11, 302, 33, 21, 1, 22, 44, 2, 11, 182, 33],
 [51, 3, 131, 2, 11, 302, 33, 21, 1, 22, 44, 2, 11, 182, 33, 21],
 [51, 3, 131, 2, 11, 302, 33, 21, 1, 22, 44, 2, 11, 182, 33, 21, 1],
 [51, 3, 131, 2, 11, 302, 33, 21, 1, 22, 44, 2, 11, 182, 33, 21, 1, 22],
 [37],
 [37, 20],
 [37, 20, 10],
 [37, 20, 10, 304],
 [37, 20, 10, 304, 183],
 [37, 20, 10, 304, 183, 56],
 [37, 20, 10, 304, 183, 56, 305],
 [37, 20, 10, 304, 183, 56, 305, 306],
 [37, 20, 10, 304, 183, 56, 305, 306, 179],
 [37, 20, 10, 304, 183, 56, 305, 306, 179, 12],
 [37, 20, 10, 304, 183, 56, 305, 306, 179, 12, 307],
 [57],
 [57, 184],
 [57, 184, 3],
 [57, 184, 3, 46],
 [57, 184, 3, 46, 5],
 [57, 184, 3, 46, 5, 185],
 [57, 184, 3, 46, 5, 185, 309],
 [57, 184, 3, 46, 5, 185, 309, 1],
 [57, 184, 3, 46, 5, 185, 309, 1, 34],
 [57, 184, 3, 46, 5, 185, 309, 1, 34, 58],
 [57, 184, 3, 46, 5, 185, 309, 1, 34, 58, 74],
 [57, 184, 3, 46, 5, 185, 309, 1, 34, 58, 74, 310],
 [57, 184, 3, 46, 5, 185, 309, 1, 34, 58, 74, 310, 9],
 [57, 184, 3, 46, 5, 185, 309, 1, 34, 58, 74, 310, 9, 3],
 [57, 184, 3, 46, 5, 185, 309, 1, 34, 58, 74, 310, 9, 3, 132],
 [57, 184, 3, 46, 5, 185, 309, 1, 34, 58, 74, 310, 9, 3, 132, 26],
 [57, 184, 3, 46, 5, 185, 309, 1, 34, 58, 74, 310, 9, 3, 132, 26, 13],
 [57, 184, 3, 46, 5, 185, 309, 1, 34, 58, 74, 310, 9, 3, 132, 26, 13, 311],
 [57],
 [57, 59],
 [57, 59, 72],
 [57, 59, 72, 313],
 [57, 59, 72, 313, 3],
 [57, 59, 72, 313, 3, 46],
 [57, 59, 72, 313, 3, 46, 1],
 [57, 59, 72, 313, 3, 46, 1, 58],
 [315],
 [315, 54],
 [315, 54, 3],
 [315, 54, 3, 21],
 [315, 54, 3, 21, 1],
 [315, 54, 3, 21, 1, 41],
 [315, 54, 3, 21, 1, 41, 9],
 [315, 54, 3, 21, 1, 41, 9, 35],
 [315, 54, 3, 21, 1, 41, 9, 35, 186],
 [315, 54, 3, 21, 1, 41, 9, 35, 186, 21],
 [315, 54, 3, 21, 1, 41, 9, 35, 186, 21, 107],
 [315, 54, 3, 21, 1, 41, 9, 35, 186, 21, 107, 60],
 [315, 54, 3, 21, 1, 41, 9, 35, 186, 21, 107, 60, 2],
 [315, 54, 3, 21, 1, 41, 9, 35, 186, 21, 107, 60, 2, 187],
 [315, 54, 3, 21, 1, 41, 9, 35, 186, 21, 107, 60, 2, 187, 27],
 [315, 54, 3, 21, 1, 41, 9, 35, 186, 21, 107, 60, 2, 187, 27, 316],
 [315, 54, 3, 21, 1, 41, 9, 35, 186, 21, 107, 60, 2, 187, 27, 316, 26],
 [315, 54, 3, 21, 1, 41, 9, 35, 186, 21, 107, 60, 2, 187, 27, 316, 26, 5],
 [315, 54, 3, 21, 1, 41, 9, 35, 186, 21, 107, 60, 2, 187, 27, 316, 26, 5, 317],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188,
  3],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188,
  3,
  1],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188,
  3,
  1,
  84],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188,
  3,
  1,
  84,
  2],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188,
  3,
  1,
  84,
  2,
  318],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188,
  3,
  1,
  84,
  2,
  318,
  74],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188,
  3,
  1,
  84,
  2,
  318,
  74,
  107],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188,
  3,
  1,
  84,
  2,
  318,
  74,
  107,
  60],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188,
  3,
  1,
  84,
  2,
  318,
  74,
  107,
  60,
  2],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188,
  3,
  1,
  84,
  2,
  318,
  74,
  107,
  60,
  2,
  187],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188,
  3,
  1,
  84,
  2,
  318,
  74,
  107,
  60,
  2,
  187,
  9],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188,
  3,
  1,
  84,
  2,
  318,
  74,
  107,
  60,
  2,
  187,
  9,
  27],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188,
  3,
  1,
  84,
  2,
  318,
  74,
  107,
  60,
  2,
  187,
  9,
  27,
  319],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188,
  3,
  1,
  84,
  2,
  318,
  74,
  107,
  60,
  2,
  187,
  9,
  27,
  319,
  19],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188,
  3,
  1,
  84,
  2,
  318,
  74,
  107,
  60,
  2,
  187,
  9,
  27,
  319,
  19,
  11],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188,
  3,
  1,
  84,
  2,
  318,
  74,
  107,
  60,
  2,
  187,
  9,
  27,
  319,
  19,
  11,
  17],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188,
  3,
  1,
  84,
  2,
  318,
  74,
  107,
  60,
  2,
  187,
  9,
  27,
  319,
  19,
  11,
  17,
  85],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188,
  3,
  1,
  84,
  2,
  318,
  74,
  107,
  60,
  2,
  187,
  9,
  27,
  319,
  19,
  11,
  17,
  85,
  189],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188,
  3,
  1,
  84,
  2,
  318,
  74,
  107,
  60,
  2,
  187,
  9,
  27,
  319,
  19,
  11,
  17,
  85,
  189,
  320],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188,
  3,
  1,
  84,
  2,
  318,
  74,
  107,
  60,
  2,
  187,
  9,
  27,
  319,
  19,
  11,
  17,
  85,
  189,
  320,
  46],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188,
  3,
  1,
  84,
  2,
  318,
  74,
  107,
  60,
  2,
  187,
  9,
  27,
  319,
  19,
  11,
  17,
  85,
  189,
  320,
  46,
  9],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188,
  3,
  1,
  84,
  2,
  318,
  74,
  107,
  60,
  2,
  187,
  9,
  27,
  319,
  19,
  11,
  17,
  85,
  189,
  320,
  46,
  9,
  321],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188,
  3,
  1,
  84,
  2,
  318,
  74,
  107,
  60,
  2,
  187,
  9,
  27,
  319,
  19,
  11,
  17,
  85,
  189,
  320,
  46,
  9,
  321,
  14],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188,
  3,
  1,
  84,
  2,
  318,
  74,
  107,
  60,
  2,
  187,
  9,
  27,
  319,
  19,
  11,
  17,
  85,
  189,
  320,
  46,
  9,
  321,
  14,
  56],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188,
  3,
  1,
  84,
  2,
  318,
  74,
  107,
  60,
  2,
  187,
  9,
  27,
  319,
  19,
  11,
  17,
  85,
  189,
  320,
  46,
  9,
  321,
  14,
  56,
  108],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188,
  3,
  1,
  84,
  2,
  318,
  74,
  107,
  60,
  2,
  187,
  9,
  27,
  319,
  19,
  11,
  17,
  85,
  189,
  320,
  46,
  9,
  321,
  14,
  56,
  108,
  86],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188,
  3,
  1,
  84,
  2,
  318,
  74,
  107,
  60,
  2,
  187,
  9,
  27,
  319,
  19,
  11,
  17,
  85,
  189,
  320,
  46,
  9,
  321,
  14,
  56,
  108,
  86,
  87],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188,
  3,
  1,
  84,
  2,
  318,
  74,
  107,
  60,
  2,
  187,
  9,
  27,
  319,
  19,
  11,
  17,
  85,
  189,
  320,
  46,
  9,
  321,
  14,
  56,
  108,
  86,
  87,
  86],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188,
  3,
  1,
  84,
  2,
  318,
  74,
  107,
  60,
  2,
  187,
  9,
  27,
  319,
  19,
  11,
  17,
  85,
  189,
  320,
  46,
  9,
  321,
  14,
  56,
  108,
  86,
  87,
  86,
  88],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188,
  3,
  1,
  84,
  2,
  318,
  74,
  107,
  60,
  2,
  187,
  9,
  27,
  319,
  19,
  11,
  17,
  85,
  189,
  320,
  46,
  9,
  321,
  14,
  56,
  108,
  86,
  87,
  86,
  88,
  4],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188,
  3,
  1,
  84,
  2,
  318,
  74,
  107,
  60,
  2,
  187,
  9,
  27,
  319,
  19,
  11,
  17,
  85,
  189,
  320,
  46,
  9,
  321,
  14,
  56,
  108,
  86,
  87,
  86,
  88,
  4,
  190],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188,
  3,
  1,
  84,
  2,
  318,
  74,
  107,
  60,
  2,
  187,
  9,
  27,
  319,
  19,
  11,
  17,
  85,
  189,
  320,
  46,
  9,
  321,
  14,
  56,
  108,
  86,
  87,
  86,
  88,
  4,
  190,
  12],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188,
  3,
  1,
  84,
  2,
  318,
  74,
  107,
  60,
  2,
  187,
  9,
  27,
  319,
  19,
  11,
  17,
  85,
  189,
  320,
  46,
  9,
  321,
  14,
  56,
  108,
  86,
  87,
  86,
  88,
  4,
  190,
  12,
  322],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188,
  3,
  1,
  84,
  2,
  318,
  74,
  107,
  60,
  2,
  187,
  9,
  27,
  319,
  19,
  11,
  17,
  85,
  189,
  320,
  46,
  9,
  321,
  14,
  56,
  108,
  86,
  87,
  86,
  88,
  4,
  190,
  12,
  322,
  28],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188,
  3,
  1,
  84,
  2,
  318,
  74,
  107,
  60,
  2,
  187,
  9,
  27,
  319,
  19,
  11,
  17,
  85,
  189,
  320,
  46,
  9,
  321,
  14,
  56,
  108,
  86,
  87,
  86,
  88,
  4,
  190,
  12,
  322,
  28,
  1],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188,
  3,
  1,
  84,
  2,
  318,
  74,
  107,
  60,
  2,
  187,
  9,
  27,
  319,
  19,
  11,
  17,
  85,
  189,
  320,
  46,
  9,
  321,
  14,
  56,
  108,
  86,
  87,
  86,
  88,
  4,
  190,
  12,
  322,
  28,
  1,
  191],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188,
  3,
  1,
  84,
  2,
  318,
  74,
  107,
  60,
  2,
  187,
  9,
  27,
  319,
  19,
  11,
  17,
  85,
  189,
  320,
  46,
  9,
  321,
  14,
  56,
  108,
  86,
  87,
  86,
  88,
  4,
  190,
  12,
  322,
  28,
  1,
  191,
  81],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188,
  3,
  1,
  84,
  2,
  318,
  74,
  107,
  60,
  2,
  187,
  9,
  27,
  319,
  19,
  11,
  17,
  85,
  189,
  320,
  46,
  9,
  321,
  14,
  56,
  108,
  86,
  87,
  86,
  88,
  4,
  190,
  12,
  322,
  28,
  1,
  191,
  81,
  323],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188,
  3,
  1,
  84,
  2,
  318,
  74,
  107,
  60,
  2,
  187,
  9,
  27,
  319,
  19,
  11,
  17,
  85,
  189,
  320,
  46,
  9,
  321,
  14,
  56,
  108,
  86,
  87,
  86,
  88,
  4,
  190,
  12,
  322,
  28,
  1,
  191,
  81,
  323,
  17],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188,
  3,
  1,
  84,
  2,
  318,
  74,
  107,
  60,
  2,
  187,
  9,
  27,
  319,
  19,
  11,
  17,
  85,
  189,
  320,
  46,
  9,
  321,
  14,
  56,
  108,
  86,
  87,
  86,
  88,
  4,
  190,
  12,
  322,
  28,
  1,
  191,
  81,
  323,
  17,
  192],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188,
  3,
  1,
  84,
  2,
  318,
  74,
  107,
  60,
  2,
  187,
  9,
  27,
  319,
  19,
  11,
  17,
  85,
  189,
  320,
  46,
  9,
  321,
  14,
  56,
  108,
  86,
  87,
  86,
  88,
  4,
  190,
  12,
  322,
  28,
  1,
  191,
  81,
  323,
  17,
  192,
  109],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,
  14,
  4,
  55,
  188,
  3,
  1,
  84,
  2,
  318,
  74,
  107,
  60,
  2,
  187,
  9,
  27,
  319,
  19,
  11,
  17,
  85,
  189,
  320,
  46,
  9,
  321,
  14,
  56,
  108,
  86,
  87,
  86,
  88,
  4,
  190,
  12,
  322,
  28,
  1,
  191,
  81,
  323,
  17,
  192,
  109,
  85],
 [315,
  54,
  3,
  21,
  1,
  41,
  9,
  35,
  186,
  21,
  107,
  60,
  2,
  187,
  27,
  316,
  26,
  5,
  317,
  75,

### Display X (Input Sequences)
Shows a sample of the generated input sequences. Each list represents a part of a sentence, leading up to a word that the model needs to predict.

In [ ]:
y

[70,
 23,
 50,
 20,
 276,
 9,
 3,
 5,
 277,
 6,
 71,
 175,
 9,
 278,
 11,
 279,
 72,
 280,
 71,
 176,
 3,
 71,
 281,
 128,
 12,
 282,
 21,
 50,
 177,
 22,
 283,
 36,
 44,
 71,
 284,
 22,
 45,
 178,
 179,
 2,
 53,
 17,
 54,
 31,
 3,
 23,
 180,
 104,
 3,
 5,
 285,
 4,
 129,
 3,
 23,
 180,
 81,
 3,
 5,
 286,
 105,
 11,
 9,
 287,
 32,
 288,
 18,
 73,
 10,
 289,
 13,
 5,
 55,
 290,
 82,
 11,
 291,
 292,
 3,
 294,
 295,
 3,
 130,
 7,
 26,
 131,
 2,
 11,
 181,
 296,
 44,
 181,
 297,
 10,
 2,
 106,
 5,
 83,
 6,
 299,
 300,
 106,
 5,
 83,
 6,
 301,
 3,
 131,
 2,
 11,
 302,
 33,
 21,
 1,
 22,
 44,
 2,
 11,
 182,
 33,
 21,
 1,
 22,
 303,
 20,
 10,
 304,
 183,
 56,
 305,
 306,
 179,
 12,
 307,
 308,
 184,
 3,
 46,
 5,
 185,
 309,
 1,
 34,
 58,
 74,
 310,
 9,
 3,
 132,
 26,
 13,
 311,
 312,
 59,
 72,
 313,
 3,
 46,
 1,
 58,
 314,
 54,
 3,
 21,
 1,
 41,
 9,
 35,
 186,
 21,
 107,
 60,
 2,
 187,
 27,
 316,
 26,
 5,
 317,
 75,
 14,
 4,
 55,
 188,
 3,
 1,
 84,
 2,
 318,
 74,
 107,
 60,
 2,
 187,
 9,
 27,
 319,
 19,
 11,
 17,
 85,
 189,
 320,
 46,
 9,
 321,
 14,
 56,
 108,
 86,
 87,
 86,
 88,
 4,
 190,
 12,
 322,
 28,
 1,
 191,
 81,
 323,
 17,
 192,
 109,
 85,
 52,
 89,
 88,
 6,
 61,
 193,
 108,
 324,
 41,
 4,
 109,
 85,
 13,
 4,
 70,
 23,
 33,
 325,
 133,
 189,
 87,
 7,
 88,
 110,
 7,
 326,
 8,
 134,
 2,
 194,
 9,
 135,
 6,
 61,
 327,
 328,
 90,
 24,
 6,
 61,
 22,
 60,
 2,
 329,
 17,
 136,
 14,
 1,
 195,
 62,
 27,
 47,
 25,
 1,
 62,
 27,
 111,
 34,
 112,
 17,
 330,
 111,
 34,
 112,
 12,
 196,
 18,
 113,
 1,
 331,
 7,
 12,
 332,
 33,
 81,
 56,
 47,
 1,
 137,
 333,
 91,
 197,
 107,
 334,
 137,
 63,
 81,
 64,
 138,
 198,
 76,
 7,
 114,
 114,
 114,
 92,
 13,
 199,
 47,
 25,
 1,
 52,
 139,
 18,
 19,
 335,
 42,
 64,
 17,
 200,
 140,
 64,
 17,
 336,
 27,
 7,
 135,
 337,
 64,
 201,
 47,
 338,
 5,
 202,
 93,
 7,
 339,
 42,
 90,
 2,
 203,
 340,
 204,
 5,
 94,
 341,
 6,
 342,
 2,
 205,
 27,
 2,
 71,
 343,
 14,
 56,
 23,
 90,
 2,
 205,
 27,
 2,
 71,
 344,
 1,
 195,
 345,
 9,
 2,
 5,
 346,
 347,
 141,
 1,
 52,
 206,
 9,
 142,
 67,
 10,
 11,
 38,
 348,
 38,
 207,
 32,
 38,
 45,
 39,
 182,
 143,
 39,
 67,
 15,
 349,
 14,
 25,
 39,
 350,
 1,
 144,
 21,
 145,
 208,
 209,
 10,
 351,
 352,
 353,
 7,
 4,
 178,
 6,
 1,
 67,
 34,
 11,
 354,
 355,
 14,
 25,
 39,
 16,
 41,
 1,
 210,
 356,
 1,
 2,
 40,
 357,
 7,
 358,
 2,
 359,
 211,
 7,
 212,
 360,
 198,
 361,
 38,
 7,
 62,
 38,
 4,
 135,
 1,
 16,
 39,
 67,
 10,
 11,
 175,
 115,
 1,
 95,
 362,
 6,
 4,
 59,
 14,
 39,
 19,
 62,
 1,
 5,
 188,
 6,
 38,
 12,
 39,
 363,
 1,
 16,
 364,
 136,
 42,
 52,
 146,
 38,
 52,
 213,
 38,
 52,
 365,
 7,
 52,
 366,
 36,
 44,
 39,
 16,
 62,
 203,
 43,
 39,
 113,
 1,
 367,
 89,
 38,
 58,
 43,
 39,
 113,
 1,
 368,
 7,
 369,
 38,
 43,
 209,
 10,
 370,
 46,
 371,
 9,
 372,
 27,
 4,
 373,
 374,
 375,
 3,
 5,
 214,
 376,
 13,
 377,
 67,
 10,
 20,
 378,
 147,
 8,
 379,
 2,
 88,
 14,
 8,
 40,
 8,
 20,
 380,
 27,
 147,
 8,
 381,
 2,
 148,
 116,
 6,
 15,
 3,
 10,
 134,
 26,
 149,
 4,
 116,
 6,
 382,
 3,
 10,
 383,
 26,
 149,
 4,
 116,
 6,
 384,
 3,
 10,
 385,
 26,
 149,
 7,
 4,
 116,
 6,
 54,
 3,
 10,
 150,
 26,
 386,
 3,
 10,
 5,
 215,
 6,
 15,
 14,
 5,
 215,
 6,
 387,
 12,
 113,
 388,
 389,
 85,
 55,
 151,
 7,
 5,
 391,
 392,
 152,
 3,
 4,
 393,
 394,
 3,
 21,
 117,
 2,
 118,
 216,
 50,
 22,
 212,
 129,
 395,
 15,
 1,
 72,
 396,
 74,
 32,
 43,
 32,
 48,
 147,
 8,
 15,
 1,
 397,
 72,
 398,
 32,
 399,
 8,
 15,
 1,
 13,
 152,
 96,
 47,
 8,
 49,
 10,
 58,
 154,
 129,
 96,
 6,
 217,
 14,
 152,
 13,
 119,
 120,
 3,
 35,
 8,
 32,
 1,
 42,
 218,
 12,
 17,
 219,
 400,
 29,
 401,
 3,
 29,
 219,
 42,
 218,
 12,
 43,
 8,
 402,
 403,
 17,
 220,
 404,
 95,
 406,
 1,
 22,
 407,
 1,
 408,
 409,
 410,
 6,
 411,
 1,
 412,
 68,
 1,
 20,
 35,
 77,
 2,
 15,
 413,
 18,
 222,
 223,
 13,
 414,
 16,
 41,
 1,
 5,
 415,
 82,
 193,
 40,
 12,
 223,
 13,
 5,
 416,
 16,
 41,
 1,
 5,
 417,
 3,
 13,
 4,
 419,
 6,
 4,
 224,
 7,
 9,
 67,
 11,
 214,
 48,
 77,
 2,
 77,
 2,
 62,
 5,
 420,
 32,
 421,
 224,
 5,
 422,
 423,
 1,
 22,
 1,
 12,
 3,
 425,
 44,
 192,
 120,
 3,
 35,
 31,
 426,
 18,
 3,
 427,
 44,
 225,
 1,
 121,
 17,
 428,
 2,
 11,
 226,
 97,
 61,
 155,
 227,
 25,
 1,
 121,
 61,
 2,
 11,
 36,
 226,
 97,
 61,
 36,
 155,
 429,
 3,
 430,
 2,
 53,
 72,
 431,
 63,
 122,
 432,
 1,
 53,
 42,
 433,
 12,
 1,
 228,
 23,
 133,
 10,
 20,
 434,
 63,
 24,
 13,
 119,
 435,
 1,
 137,
 98,
 436,
 19,
 84,
 1,
 48,
 5,
 2,
 438,
 229,
 19,
 84,
 1,
 439,
 55,
 93,
 115,
 156,
 43,
 9,
 441,
 1,
 1,
 230,
 35,
 442,
 36,
 12,
 1,
 97,
 4,
 36,
 99,
 1,
 19,
 58,
 4,
 36,
 12,
 1,
 231,
 4,
 36,
 443,
 111,
 444,
 232,
 9,
 3,
 446,
 233,
 17,
 200,
 128,
 14,
 447,
 76,
 448,
 157,
 12,
 197,
 12,
 9,
 3,
 10,
 449,
 75,
 3,
 123,
 3,
 60,
 2,
 146,
 1,
 1,
 56,
 234,
 2,
 112,
 4,
 190,
 450,
 451,
 452,
 24,
 6,
 118,
 16,
 49,
 94,
 99,
 14,
 50,
 16,
 49,
 236,
 99,
 28,
 94,
 158,
 4,
 453,
 160,
 150,
 3,
 14,
 4,
 454,
 94,
 237,
 1,
 456,
 3,
 15,
 14,
 5,
 161,
 457,
 144,
 7,
 139,
 91,
 458,
 97,
 2,
 58,
 162,
 10,
 459,
 461,
 16,
 58,
 4,
 239,
 3,
 2,
 462,
 20,
 114,
 463,
 12,
 464,
 19,
 11,
 5,
 163,
 6,
 240,
 3,
 34,
 110,
 465,
 2,
 11,
 ...]

### Display y (Target Words)
Shows a sample of the target words, which are the next words corresponding to each input sequence in `X`.

In [ ]:
len(X)

2257

### Display Length of X
Outputs the total number of input sequences created for training.

In [ ]:
len(y)

2257

### Display Length of y
Outputs the total number of target words, which should match the length of `X`.

In [ ]:
max_len = max(len(x) for x in X)
print(max_len)

197

### Calculate Maximum Sequence Length
Determines the length of the longest sequence in `X`. This `max_len` will be used to pad all input sequences to a uniform length, which is required for neural network inputs.

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
X_padded = pad_sequences(X , maxlen=max_len , padding='pre')

### Pad Input Sequences
Pads all input sequences in `X` to `max_len`. Padding is applied at the beginning (`padding='pre'`) with zeros, ensuring all input sequences have the same dimensions for the model. This requires `pad_sequences` from Keras.

In [ ]:
X_padded

array([[ 0,  0,  0, ...,  0,  0, 30],
       [ 0,  0,  0, ...,  0, 30, 70],
       [ 0,  0,  0, ..., 30, 70, 23],
       ...,
       [ 0,  0,  0, ...,  9,  3,  2],
       [ 0,  0,  0, ...,  3,  2, 64],
       [ 0,  0,  0, ...,  2, 64, 26]], dtype=int32)

### Display Padded Input Sequences
Shows the `X_padded` array, demonstrating how sequences have been transformed into uniform-length arrays.

In [ ]:
y = np.array(y)

### Convert Target Words to NumPy Array
Converts the list of target words `y` into a NumPy array, which is a required format for Keras training.

In [ ]:
X_padded.shape

(2257, 197)

### Display Shape of Padded Input Sequences
Outputs the shape of `X_padded` (number of samples, `max_len`).

In [ ]:
y.shape

(2257,)

### Display Shape of Target Words
Outputs the shape of the `y` array.

In [ ]:
from tensorflow.keras.utils import to_categorical
y_one_hot = to_categorical(y , num_classes=vocab_size)

### One-Hot Encode Target Words
Converts the integer-encoded target words `y` into a one-hot encoded format. This is necessary for training with `categorical_crossentropy` loss, where each target word becomes a vector of zeros with a `1` at the index corresponding to the word's ID. The `num_classes` is set to `vocab_size` to ensure the correct output dimension.

In [ ]:
y_one_hot.shape

(2257, 763)

### Display Shape of One-Hot Encoded Targets
Outputs the shape of `y_one_hot`, which should be `(number of samples, vocab_size)`.

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding , SimpleRNN , LSTM , Dense

In [ ]:
# Import necessary components for building neural network models.
# `Sequential` is used for stacking layers linearly.
# `Embedding` layer transforms word indices into dense vectors.
# `SimpleRNN` and `LSTM` are recurrent layers for processing sequences.
# `Dense` layer is a standard fully connected neural network layer.
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding , SimpleRNN , LSTM , Dense

## Model Definition and Training
This section defines, compiles, and trains the Recurrent Neural Network (RNN) and Long Short-Term Memory (LSTM) models for word prediction.

In [ ]:
embedding_dim = 50
rnn_units = 128 #hidden layer neurons

### Set Embedding and RNN Units Dimensions
Defines the `embedding_dim` (the size of the vector space in which words will be embedded) and `rnn_units` (the number of units in the SimpleRNN and LSTM layers, representing the hidden state size).

In [ ]:
rnn_model = Sequential()

rnn_model.add(
    Embedding(input_dim=vocab_size , output_dim=embedding_dim , input_length=max_len)
)

rnn_model.add(SimpleRNN(units=rnn_units))
rnn_model.add(Dense(units=vocab_size , activation='softmax'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

### Define SimpleRNN Model
Constructs a sequential RNN model:
-   **Embedding Layer**: Maps integer word indices to dense vectors of fixed size (`embedding_dim`). `input_dim` is `vocab_size` (total unique words), `output_dim` is `embedding_dim`, and `input_length` is `max_len` (length of input sequences). This layer learns to represent words in a meaningful vector space.
-   **SimpleRNN Layer**: A basic recurrent layer with `rnn_units` neurons, capable of processing sequences and retaining information from previous steps.
-   **Dense Layer**: The output layer with `vocab_size` units (one for each possible next word) and `softmax` activation to output probabilities for each word in the vocabulary. The word with the highest probability is the model's prediction.

In [ ]:
rnn_model.compile(loss='categorical_crossentropy' , optimizer='adam' , metrics=['accuracy'])

### Compile SimpleRNN Model
Compiles the RNN model, preparing it for training:
-   **Loss Function**: `categorical_crossentropy` is used as it's suitable for multi-class classification where targets are one-hot encoded. It measures the error between predicted probabilities and true one-hot labels.
-   **Optimizer**: `adam` is a popular and effective optimization algorithm that adapts the learning rate during training.
-   **Metrics**: `accuracy` is tracked to evaluate the model's performance during training and validation.

In [ ]:
rnn_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

### Display SimpleRNN Model Summary
Prints a summary of the RNN model's architecture, including layer types, output shapes of each layer, and the total number of trainable and non-trainable parameters. This helps in understanding the model's complexity and structure.

In [ ]:
lstm_model = Sequential()
lstm_model.add(
    Embedding(input_dim=vocab_size , output_dim=embedding_dim , input_length=max_len)
)

lstm_model.add(LSTM(units=rnn_units))
lstm_model.add(Dense(units=vocab_size , activation='softmax'))

### Define LSTM Model
Constructs a sequential LSTM model, similar to the RNN but using an LSTM layer instead of SimpleRNN:
-   **Embedding Layer**: Same as in the RNN model, mapping word indices to dense vectors.
-   **LSTM Layer**: A type of recurrent neural network that is better at learning long-term dependencies than simple RNNs. It includes 'gates' that regulate the flow of information, making it effective for tasks like language modeling.
-   **Dense Layer**: The output layer with `vocab_size` units and `softmax` activation to predict word probabilities.

In [ ]:
lstm_model.compile(loss='categorical_crossentropy' , optimizer='adam' , metrics=['accuracy'])

### Compile LSTM Model
Compiles the LSTM model with the same loss function (`categorical_crossentropy`), optimizer (`adam`), and metrics (`accuracy`) as the RNN model.

In [ ]:
lstm_model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

### Display LSTM Model Summary
Prints a summary of the LSTM model's architecture, showing its layers, output shapes, and parameter count. This allows for a comparison with the SimpleRNN model.

In [ ]:
epochs = 10
batch_size = 128

### Set Training Parameters
Defines the `epochs` (number of times the model will iterate over the entire dataset) and `batch_size` (number of samples per gradient update during training). These parameters control the training process.

In [ ]:
history_rnn = rnn_model.fit(
    X_padded , y_one_hot ,
    epochs=epochs ,
    batch_size=batch_size ,
    validation_split=0.1
)

Epoch 1/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 8s 298ms/step - accuracy: 0.0089 - loss: 6.5213 - val_accuracy: 0.0177 - val_loss: 6.3205
Epoch 2/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 4s 243ms/step - accuracy: 0.0394 - loss: 5.9235 - val_accuracy: 0.0177 - val_loss: 6.2207
Epoch 3/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 6s 356ms/step - accuracy: 0.0379 - loss: 5.7171 - val_accuracy: 0.0177 - val_loss: 6.3843
Epoch 4/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 5s 297ms/step - accuracy: 0.0335 - loss: 5.6903 - val_accuracy: 0.0177 - val_loss: 6.4600
Epoch 5/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 3s 211ms/step - accuracy: 0.0394 - loss: 5.6771 - val_accuracy: 0.0177 - val_loss: 6.5041
Epoch 6/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 3s 216ms/step - accuracy: 0.0394 - loss: 5.6720 - val_accuracy: 0.0177 - val_loss: 6.5407
Epoch 7/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 5s 348ms/step - accuracy: 0.0335 - loss: 5.6685 - val_accuracy: 0.0177 - val_loss: 6.6060
Epoch 8/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 4s 220ms/step - accuracy: 0.0394 - loss: 5.6591 - val_accuracy: 0.0177 - val_loss: 6.5865
Epoch 9/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 4s 276ms/step - accuracy: 0.0487 - loss: 5.6468 - val_accuracy: 0.0177 - val_loss: 6.6333
Epoch 10/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 6s 333ms/step - accuracy: 0.0394 - loss: 5.6307 - val_accuracy: 0.0265 - val_loss: 6.5994

### Train SimpleRNN Model
Trains the `rnn_model` using the padded input sequences `X_padded` and one-hot encoded target words `y_one_hot`. A `validation_split` of 0.1 means 10% of the data will be used for validation to monitor the model's performance on unseen data during training and help detect overfitting.

In [ ]:
lstm_model.save("lstm_model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

### Save LSTM Model
Saves the trained `lstm_model` to an HDF5 file named `lstm_model.h5`. This allows for loading the trained model later without needing to retrain it, saving computation time. The warning indicates a recommendation to use the newer Keras native format (.keras) but HDF5 is still supported.

In [ ]:
index_to_word = {}

for word , index in word_index.items():
  index_to_word[index] = word

In [ ]:
# Create a reverse mapping from word index to word string.
# This dictionary is crucial for converting the model's numerical predictions (integer indices)
# back into human-readable words from the vocabulary.
index_to_word = {}
for word , index in word_index.items():
  index_to_word[index] = word

## Prediction and Text Generation
This section contains functions for predicting the next word and generating continuous text using the trained models.

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

### Import `pad_sequences`
Imports `pad_sequences` from `tensorflow.keras.preprocessing.sequence` again, although it was already imported earlier (in cell `fUDc0leGG0nw`). This is needed for preprocessing input text for the `predictor` function to ensure all input sequences have a uniform length.

In [ ]:
def predictor(model , tokenizer , text , max_len):
  text = text.lower()
  seq = tokenizer.texts_to_sequences([text])[0]
  seq = pad_sequences([seq] , maxlen=max_len , padding='pre')

  pred = model.predict(seq , verbose=0)
  pre_index = np.argmax(pred)
  return index_to_word[pre_index]

### Define `predictor` Function
This function takes a trained model, tokenizer, input text, and maximum sequence length, and predicts the next word:
1.  **Lowercase Text**: Converts the input `text` to lowercase for consistency with training data.
2.  **Tokenize Text**: Converts the cleaned input text into a numerical sequence using the pre-fitted `tokenizer`.
3.  **Pad Sequence**: Pads the numerical sequence to `max_len` using `maxlen` (ensuring uniform input size for the model) with `padding='pre'` (adding zeros to the beginning).
4.  **Predict Next Word**: Uses the `model` to predict the probability distribution over all possible next words. `verbose=0` suppresses output during prediction.
5.  **Get Predicted Word**: `np.argmax(pred)` finds the index of the word with the highest predicted probability. This index is then used to retrieve the actual word string from the `index_to_word` dictionary.

In [ ]:
seed_text = "life is the best"
next_word = predictor(lstm_model , tokenizer , seed_text , max_len)
print(next_word)

doesnt

### Test `predictor` Function
Demonstrates the `predictor` function by providing a `seed_text` ("life is the best") and then printing the `next_word` predicted by the `lstm_model`.

In [ ]:
def generate_text(model , tokenizer , seed_text , max_len ,  n_words ):
  for _ in range(n_words):
    next_word = predictor(model , tokenizer , seed_text , max_len)
    if next_word == "":
      break
    seed_text += " " + next_word
  return seed_text

### Define `generate_text` Function
This function generates a sequence of `n_words` starting from a given `seed_text`:
1.  **Iterative Prediction**: It loops `n_words` times, in each iteration calling the `predictor` function to get the next word based on the current `seed_text`.
2.  **Concatenate Words**: The predicted `next_word` is appended to the `seed_text` to form a growing sequence.
3.  **Break Condition**: If the `predictor` returns an empty string (e.g., if it can't confidently predict a word or hits a special token), the generation process stops.
4.  **Return Generated Text**: The complete `seed_text` containing the original phrase and all generated words is returned.

In [ ]:
seed = "the meaning of life"
generate_text = generate_text(lstm_model , tokenizer , seed , max_len , 10)
print(generate_text)

the meaning of life seem either failing failing fear failing ones failing failing there

### Test `generate_text` Function
Provides an initial `seed` phrase ("the meaning of life") and uses the `generate_text` function with the `lstm_model` to generate 10 additional words. The complete generated text, including the seed phrase and the new words, is then printed.

In [ ]:
import pickle
with open("tokenizer.pkl" , "wb") as f:
  pickle.dump(tokenizer , f)

In [ ]:
with open("mwx_len.pkl" , "wb") as f:
  pickle.dump(max_len , f)